from __future__ import annotations

from pathlib import Path


def export_gm3_factor(expression: str, name: str = "ai_factor_v2", out_dir: str = "generated") -> Path:
    """Generate a GM3-compatible selector function.

    The generated function is intentionally pure: it only consumes a pandas DataFrame
    and returns a numeric Series, so it can be wrapped by gm3_factor/select registration.
    """
    safe = expression.replace("\n", " ")
    code = f'''from __future__ import annotations\n\nimport numpy as np\nimport pandas as pd\n\n\ndef {name}(df: pd.DataFrame) -> pd.Series:\n    """Auto-generated by factor_gen.\n\n    Expression: {safe}\n    """\n    ret1 = df["close"].pct_change()\n    ret5 = df["close"].pct_change(5)\n    ret10 = df["close"].pct_change(10)\n    range_ = (df["high"] - df["low"]) / df["close"].replace(0, np.nan)\n    body = (df["close"] - df["open"]) / df["close"].replace(0, np.nan)\n    close_pos = (df["close"] - df["low"]) / (df["high"] - df["low"]).replace(0, np.nan)\n    vol_chg = df["volume"].replace(0, np.nan).pct_change()\n    vol_z20 = (df["volume"] - df["volume"].rolling(20).mean()) / df["volume"].rolling(20).std()\n    ma_gap5 = df["close"] / df["close"].rolling(5).mean() - 1\n    ma_gap20 = df["close"] / df["close"].rolling(20).mean() - 1\n    score = {safe}\n    return pd.Series(score, index=df.index, name="{name}").replace([np.inf, -np.inf], np.nan).fillna(0.0)\n'''
    path = Path(out_dir) / f"{name}.py"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(code, encoding="utf-8")
    return path
