from __future__ import annotations

from pathlib import Path


def export_gm3_factor(expression: str, name: str = "ai_factor_v2", out_dir: str = "generated") -> Path:
    safe = expression.replace("\n", " ")
    code = f'''from __future__ import annotations

import numpy as np
import pandas as pd


def identity(x): return x

def neg(x): return -x

def abs(x): return x.abs()

def square(x): return np.sign(x) * np.square(np.clip(x, -5, 5))

def tanh(x): return np.tanh(x)


def {name}(df: pd.DataFrame) -> pd.Series:
    """Auto-generated by factor_gen V2. Expression: {safe}"""
    ret1 = df["close"].pct_change()
    ret5 = df["close"].pct_change(5)
    ret10 = df["close"].pct_change(10)
    range = (df["high"] - df["low"]) / df["close"].replace(0, np.nan)
    body = (df["close"] - df["open"]) / df["close"].replace(0, np.nan)
    close_pos = (df["close"] - df["low"]) / (df["high"] - df["low"]).replace(0, np.nan)
    vol_chg = df["volume"].replace(0, np.nan).pct_change()
    vol_z20 = (df["volume"] - df["volume"].rolling(20).mean()) / df["volume"].rolling(20).std()
    ma_gap5 = df["close"] / df["close"].rolling(5).mean() - 1
    ma_gap20 = df["close"] / df["close"].rolling(20).mean() - 1
    score = {safe}
    return pd.Series(score, index=df.index, name="{name}").replace([np.inf, -np.inf], np.nan).fillna(0.0)
'''
    path = Path(out_dir) / f"{name}.py"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(code, encoding="utf-8")
    return path
