from __future__ import annotations
from pathlib import Path

def export_gm3_factor(best):
    out=Path("generated"); out.mkdir(exist_ok=True)
    expr=best["expression"]; r=best["report"]
    p=out/"ai_factor_v4.py"
    p.write_text(f'''# Auto-generated by factor_gen V4\n# expression: {expr}\n# validation: mean_ic={r.mean_ic:.6f}, median_ic={r.median_ic:.6f}\n\ndef factor(df):\n    # Replace column names only if your GM3 select context uses different aliases.\n    return {expr.replace("ret1","df['ret1']").replace("range","df['range']").replace("body","df['body']").replace("vol_chg","df['vol_chg']").replace("mom5","df['mom5']").replace("mom20","df['mom20']").replace("vol20","df['vol20']")}\n''',encoding="utf-8")
    return str(p)
