from __future__ import annotations
import logging
from dataclasses import dataclass
from pathlib import Path
import numpy as np
import pandas as pd
from scipy.stats import rankdata
from .gm3_adapter import GM3DataAdapter
from .ai.transformer_v42 import V42Transformer
LOG=logging.getLogger("factor_gen.v42")
BASE_FEATURES=["ret1","ret5","range","body","close_pos","vol_z","volatility","trend"]
FEATURES=BASE_FEATURES+["ai_score"]
@dataclass
class Result:
    status:str; mean_ic:float; median_ic:float; ic_std:float; ic_ir:float; positive_ratio:float; formula:str; test_mean_ic:float

def make_panel(df):
    x=df.copy().sort_values(["symbol","eob"]); g=x.groupby("symbol",group_keys=False)
    x["ret1"]=g.close.pct_change(); x["ret5"]=g.close.pct_change(5); x["range"]=(x.high-x.low)/(x.close.abs()+1e-8); x["body"]=(x.close-x.open)/(x.open.abs()+1e-8); x["close_pos"]=(x.close-x.low)/(x.high-x.low+1e-8)
    lv=np.log1p(x.volume.clip(lower=0)); x["vol_z"]=lv-g.volume.transform(lambda s:np.log1p(s.clip(lower=0)).rolling(20,min_periods=5).mean()); x["volatility"]=g.ret1.transform(lambda s:s.rolling(20,min_periods=10).std()); x["trend"]=g.close.transform(lambda s:s.rolling(20,min_periods=10).mean())/(x.close.abs()+1e-8)-1; x["target"]=g.close.shift(-1)/x.close-1
    return x.replace([np.inf,-np.inf],np.nan).dropna(subset=BASE_FEATURES+["target"]).reset_index(drop=True)

def split_by_time(df,train=.6,valid=.2):
    dates=np.sort(df.eob.unique()); a=int(len(dates)*train); b=int(len(dates)*(train+valid)); return df[df.eob.isin(dates[:a])].copy(),df[df.eob.isin(dates[a:b])].copy(),df[df.eob.isin(dates[b:])].copy()

def add_ai_score(train,valid,test):
    model=V42Transformer(); model.fit(train,BASE_FEATURES,"target")
    for part in (train,valid,test): part["ai_score"]=model.predict(part,BASE_FEATURES)
    return tuple(p.dropna(subset=["ai_score"]) for p in (train,valid,test))

def cs_ic(score,y,dates):
    tmp=pd.DataFrame({"s":score,"y":y,"d":dates}); vals=[]
    for _,g in tmp.groupby("d",sort=False):
        if len(g)<10 or g.s.nunique()<2 or g.y.nunique()<2: continue
        vals.append(np.corrcoef(rankdata(g.s),rankdata(g.y))[0,1])
    return np.asarray(vals,float)

def exact_ic(df,w): return cs_ic(df[FEATURES].to_numpy(float)@w,df.target.to_numpy(float),df.eob)

def million_screen(train,budget=1_000_000,seed=42,batch=100_000):
    z=[]; yy=[]
    for _,g in train.groupby("eob",sort=False):
        if len(g)<10: continue
        xx=g[FEATURES].to_numpy(float); tt=g.target.to_numpy(float); z.append((xx-np.nanmean(xx,0))/(np.nanstd(xx,0)+1e-8)); yy.append((tt-np.nanmean(tt))/(np.nanstd(tt)+1e-8))
    if not z:return []
    Y=np.concatenate(yy); corr=np.nan_to_num(np.vstack(z).T@Y/len(Y)); rng=np.random.default_rng(seed); best=[]
    for start in range(0,budget,batch):
        n=min(batch,budget-start); W=rng.normal(size=(n,len(FEATURES))); W/=np.linalg.norm(W,axis=1,keepdims=True)+1e-12; a=np.abs(W@corr); k=min(1000,n); idx=np.argpartition(a,-k)[-k:]; best.extend((float(a[i]),W[i].copy()) for i in idx); LOG.info("screen %d/%d",min(start+n,budget),budget)
    best.sort(key=lambda x:x[0],reverse=True); return [w for _,w in best[:1000]]

def formula_text(w,df_prefix=""):
    return " + ".join(f"({w[j]:+.7f}*{df_prefix}{FEATURES[j]})" for j in range(len(FEATURES)))

def search(train,valid,test,budget=1_000_000):
    candidates=million_screen(train,budget); scored=[]
    for i,w in enumerate(candidates,1):
        vi=exact_ic(valid,w)
        if len(vi)>=20: scored.append((float(np.nanmean(vi)),w,vi))
        if i%100==0:LOG.info("validation %d/%d",i,len(candidates))
    scored.sort(key=lambda x:x[0],reverse=True)
    for score,w,vi in scored[:20]:
        ti=exact_ic(test,w)
        if len(ti)<20:continue
        m,med,sd=float(np.nanmean(ti)),float(np.nanmedian(ti)),float(np.nanstd(ti)); ir=m/(sd+1e-12); pos=float(np.mean(ti>0))
        if score>.03 and med>.03 and m>.03 and pos>=.60 and ir>=.50: return Result("PASS",m,med,sd,ir,pos,formula_text(w),m)
    if scored:
        score,w,vi=scored[0]; ti=exact_ic(test,w); m=float(np.nanmean(ti)) if len(ti) else float("nan"); return Result("FAIL",float(np.nanmean(vi)),float(np.nanmedian(vi)),float(np.nanstd(vi)),float(np.nanmean(vi)/(np.nanstd(vi)+1e-12)),float(np.mean(vi>0)),formula_text(w),m)
    return Result("NO_CANDIDATE",float("nan"),float("nan"),float("nan"),float("nan"),0.0,"",float("nan"))

def export_factor(result,out="generated/ai_factor_v42.py"):
    Path(out).parent.mkdir(parents=True,exist_ok=True)
    expression=formula_text([float(x) for x in []]) if False else result.formula
    # Replace feature tokens with dataframe column access so the generated file is executable.
    for name in FEATURES: expression=expression.replace(name,f'df["{name}"]')
    code='# Auto-generated by factor_gen V4.2 after an unseen-test gate.\n\ndef factor(df):\n    return '+expression+'\n'
    Path(out).write_text(code,encoding="utf-8"); return out

def run(config=None):
    c=config or {}; data=GM3DataAdapter(index=c.get("index","SHSE.000300"),symbols=c.get("symbols"),count=int(c.get("bars",1200))).load(); LOG.info("GM3 rows=%d symbols=%d",len(data),data.symbol.nunique()); panel=make_panel(data); train,valid,test=split_by_time(panel); train,valid,test=add_ai_score(train,valid,test); LOG.info("split rows train=%d valid=%d test=%d",len(train),len(valid),len(test)); result=search(train,valid,test,int(c.get("candidates",1_000_000))); LOG.info("FINAL %s testIC=%.5f mean=%.5f median=%.5f IR=%.3f positive=%.2f",result.status,result.test_mean_ic,result.mean_ic,result.median_ic,result.ic_ir,result.positive_ratio); 
    if result.status=="PASS": LOG.info("factor exported: %s",export_factor(result))
    return result
