from pathlib import Path
import json

def write_report(out,report):
    out=Path(out); out.mkdir(parents=True,exist_ok=True); (out/'report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2,default=str),encoding='utf-8')

def write_factor(out,expression,name='best_factor'):
    out=Path(out); out.mkdir(parents=True,exist_ok=True)
    code=f'''"""Auto-generated by factor_gen V3; validate before live use."""\nimport numpy as np\n\ndef factor(df):\n    c=df['close'].replace(0,np.nan); o=df['open'].replace(0,np.nan)\n    ret1=df['close'].pct_change().fillna(0.0); ret5=df['close'].pct_change(5).fillna(0.0)\n    range_pct=((df['high']-df['low'])/c).replace([np.inf,-np.inf],np.nan).fillna(0.0)\n    body_pct=((df['close']-df['open'])/o).replace([np.inf,-np.inf],np.nan).fillna(0.0)\n    close_pos=((df['close']-df['low'])/(df['high']-df['low']).replace(0,np.nan)).fillna(0.5)\n    vol_chg=df['volume'].pct_change().replace([np.inf,-np.inf],np.nan).fillna(0.0)\n    vm=df['volume'].rolling(20,min_periods=10).mean(); vs=df['volume'].rolling(20,min_periods=10).std()\n    vol_z=((df['volume']-vm)/vs).replace([np.inf,-np.inf],np.nan).fillna(0.0)\n    mom20=df['close'].pct_change(20).fillna(0.0); vol20=ret1.rolling(20,min_periods=10).std().fillna(0.0)\n    gap=df['open'].pct_change().fillna(0.0)-ret1\n    return ({expression})\n'''
    (out/f'{name}.py').write_text(code,encoding='utf-8')
